{% set name = "halide" %}
{% set version = "2017.05.03" %}
{% set sha256 = "22db6c51ad19d5621ebbada18ab2c6f4da30d6f71c3904aefc302ddadada48f9" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/halide/Halide/archive/release_{{ version.replace('.', '_') }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ldflags.patch
    - python_bindings_makefile.patch

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - clangdev
    - llvmdev
    - boost
    - zlib 1.2.*
  run:
    - python
    - boost
    - zlib 1.2.*

test:
  requires:
    - toolchain
  imports:
    - halide

about:
  home: http://halide-lang.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'a language for image processing and computational photography'

  description: |
    Halide is a new programming language designed to make it easier to write
    high-performance image processing code on modern machines. Its current front end is embedded in
    C++. Compiler targets include x86/SSE, ARM v7/NEON, CUDA, Native Client, and OpenCL.
  doc_url: http://halide-lang.org/docs/
  dev_url: https://github.com/halide/Halide

extra:
  recipe-maintainers:
    - jrk
    - minrk
