{% set name = "halide" %}
{% set version = "18.0.0" %}
{% set sha256 = "1176b42a3e2374ab38555d9316c78e39b157044b5a8e765c748bf3afd2edb351" %}
{% set build = 1 %}
{% set llvm_version = 18 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/halide/Halide/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("halide") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - clangdev   {{ llvm_version }}.*
    - llvmdev    {{ llvm_version }}.*
    - llvm       {{ llvm_version }}.*
    - lld        {{ llvm_version }}.*
    - libxml2
    - zlib
    - libpng
    - libjpeg-turbo

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  files:
    - test.cpp

outputs:
  - name: halide

  - name: halide-python
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - python
        - pybind11
        - scikit-build
        - pip
        - {{ pin_subpackage("halide", exact=True) }}
        - clangdev   {{ llvm_version }}.*
        - llvmdev    {{ llvm_version }}.*
        - llvm       {{ llvm_version }}.*
        - lld        {{ llvm_version }}.*
        - zlib
      run:
        - {{ pin_subpackage("halide", exact=True) }}
        - python
        - numpy
    test:
      imports:
        - halide
    about:
      summary: 'python bindings for halide programming language'

about:
  home: http://halide-lang.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'a language for image processing and computational photography'
  description: |
    Halide is a programming language designed to make it easier to write
    high-performance data parallel processing code on modern machines.
    Its current front end is embedded in C++. Compiler targets include
    x86/SSE, ARM v7/NEON, CUDA, Hexagon DSP, and OpenCL.
  doc_url: http://halide-lang.org/docs/
  dev_url: https://github.com/halide/Halide

extra:
  recipe-maintainers:
    - jrk
    - minrk
    - steven-johnson
    - isuruf
