appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZDFp953vV+UFYKrogg+ivEDUCvmSUC3qAR0pCih/9RmxN2v3MztZpLCS9Xx58NzbRUtBBl2uBYKsCPDIfcdd6VZ6u3MiZC69Wg42sfI7lmKTrBeflbw7reLOJfxBR95D65GVzVREuUk3tsvgbEPK6xOqrzQFZ1dFd0mPGPBuQ7nv0MNefTb5DfpaYXyy4SlcCXMVSljyQDu8gU7xI2p4gH1NH9jVb63JresISwU+rkypDBKvP6TOsNK4ezlbrWDx2TEMpGF0Vm39LyBbCzrY0Jt01onjN7C5N4RJJIuNgjee3oPyITi0kiqrUIKXwFcsUCicKauRpSFPbOoJZ2dGxIQ4ZD8e2kDO0ikUVpWKDx+dUTO+HRhpnKoXe5Y/JvoWP1ueNgGNDiEyZ0RqMLpLpKvk/n0VqhtR48ygYlcZM9pmM0L/qSwYLRWazZpDISDS0kPx00zl99a8EnjWgEuY5bXkYiZlCzDhcUlRnOIhCd115yw5jrw5NGm5ik95XPJhCBZJOoNKltMBnuu8JAFYIgpcc4p0zlSheiPYxGIlVVtiUv8Tj5zpvdbkREIB3eNNudpRxK4vVuBuXEGEbZS/DQc1BHbnwJjSqqrv+nPZbRcZa2GnAMdp4NuNMzjQlAwvXef1bA5A4vhWO3ObN+K7RZ+I/O56rnkHJyeKJDKd4FQ=}
conda_forge_output_validation: true
