travis:
  secure:
    BINSTAR_TOKEN: iJPz2kFl/YIK90oofS1n0xskBfY01VF8ABY4RdiiZWKX7uno3smcrNTSZ6AljyuYQjHmnFB19FUhvMkXBZmD+fJSpegm4+mOL67yClkomgiEb2Xon/Fkh4jqvvUdmyR7Ah1vXdGo+c0XKpZfKaek56Z0hEOghGx4LRegbIGJFs0UlH9cmpa61emCZoz5CUiau99XPhDygKMyHB0Np7YYQ39VMJFyGU+zCbGwW1IsjhdFoV+m6/fAKdPSqrG1bC9XsBGeNmpbNJtRQHeP0O3PWdUNzsbtXxm+Isl7XwQMPv8r+/HP1o1KuEV0Z2CeU3ZgAN3XpY2Ue9KK6NijSDaRWwbjkm4a4E4nLeQymqxiFtwwnktWhqcXU1IQehNRM8oEY0rusvTBNmFQpzuxWD6d6aqGcv/HINFZ7PiBpU65SVDbXyBgeQuzPZTDV/8tcBs7t0gdMUDT15qjJsA7tIVm+NuCdSTZTsBVLG6TAr002buB6OSIQvdgRTszB8L1knzIuhiZz83bt4bzpnrjlIO9OgO4QQYscU+TNJfqwbserZRAxtnhKPm4HTkx/LRDyWc7hckWV2UT8Z2iKNJUKh0MdK4YpoIqtDTV3RstxWZApFzFn0SrR59BUBLdmeHpq5tmhgt6ty9DWFG+qtIgIM6txOl7PNE4x3/76gJCwQBq6q0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
